exclude = [
    "tests/*",
    "site-packages/*",
    "venv/*",
    "migrations/*",
    "alembic/versions/*",  # still lint alembic/env.py
]

line-length = 88
indent-width = 4
target-version = "py314"

[lint]
select = [
    "E4", "E7", "E9",  # Pycodestyle errors
    "F",               # Pyflakes (undefined names, etc.)
    "I",               # isort (import ordering)
    "B",               # flake8-bugbear (common bugs / bad patterns)
    "UP",              # pyupgrade (keep Python syntax modern)
    "D1",              # pydocstyle (docstring presence only)
]
ignore = ["B008", "B904", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"]  # skip docstring checks
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
